import { motion } from "framer-motion"
import PageBanner from "../components/common/PageBanner"
import { ServiceImageShowcase } from "../components/common/ServicePageParts"
import { Smartphone, ShieldCheck, QrCode, CreditCard, RefreshCw, KeyRound, Sparkles } from "lucide-react"

export default function MobileBanking() {
  const appFeatures = [
    {
      icon: <RefreshCw className="size-6 text-primary" />,
      title: "Instant Fund Transfers",
      desc: "Perform immediate inter-bank money transfers via integrated IMPS and NEFT channels directly from your mobile dashboard."
    },
    {
      icon: <CreditCard className="size-6 text-amber-500" />,
      title: "Utility Bill Payments",
      desc: "Pay electricity bills, water utilities, mobile recharges, and insurance premiums effortlessly without queues."
    },
    {
      icon: <QrCode className="size-6 text-emerald-500" />,
      title: "QR Code Scan & Pay",
      desc: "Integrated UPI QR scanners to make direct quick payments to any retail merchant or vendor instantly."
    },
    {
      icon: <KeyRound className="size-6 text-indigo-500" />,
      title: "Biometric Login",
      desc: "Fast, high-security fingerprint and Face ID login integration keeping your banking sessions safe."
    }
  ]

  const registrationSteps = [
    { title: "Download App", desc: "Locate the ASCB Mobile Banking App on iOS App Store or Google Play Store." },
    { title: "KYC Verification", desc: "Input your linked bank account number and registered mobile number for SMS matching verification." },
    { title: "OTP Authentication", desc: "Enter the secure one-time passcode generated by our server to authenticate your device." },
    { title: "Generate MPIN", desc: "Establish your custom 4-digit mobile transaction pin (MPIN) to authorize future operations." }
  ]

  const securityGuidelines = [
    "Never share your MPIN, passwords, or transaction OTPs with anyone.",
    "Do not log in to your mobile banking app using public Wi-Fi networks.",
    "Always lock the application and exit when your banking operations are complete.",
    "Enable automated biometric authentication for an additional layer of security.",
    "Regularly update your banking application from official stores to run the latest security patches."
  ]

  return (
    <div className="bg-slate-50/50 min-h-screen pb-16">
      {/* Banner */}
      <PageBanner
        title="Mobile Banking"
        subtitle="Manage accounts, pay bills, and transfer funds securely on the go with the ASCB Digital Mobile Banking App."
        category="Facilities & Services"
      />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-16 space-y-24">
        <ServiceImageShowcase
          badge="Mobile-first banking"
          title="Your ASCB account, transfers, and alerts in one pocket-friendly experience"
          subtitle="Mobile banking helps members check balances, move money, manage payments, and stay informed without waiting at a counter."
          image="/history_modern.png"
          imageAlt="ASCB branch with mobile digital banking signage"
          imageLabel="Digital banking access"
          points={[
            "Balance and mini-statement access",
            "IMPS and NEFT transfer support",
            "Secure MPIN and OTP authentication",
            "Bill payments and QR scan support"
          ]}
          stats={[
            { value: "24/7", label: "Access" },
            { value: "OTP", label: "Auth" },
            { value: "5m", label: "Setup" }
          ]}
        />
        
        {/* Section 1: Product Intro */}
        <section className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="space-y-6"
          >
            <span className="inline-flex items-center gap-1.5 text-[10px] font-bold text-primary bg-sky-50 px-3.5 py-1 rounded-full border border-sky-100">
              <Sparkles className="size-3.5" /> SECURE MOBILE APP
            </span>
            <h2 className="text-3xl font-extrabold text-slate-900 leading-tight">
              Carry Ariyallur Cooperative Bank right in your pocket
            </h2>
            <p className="text-slate-600 text-sm leading-relaxed">
              Embrace next-generation banking convenience. Our dedicated mobile app is built with top-tier encryption algorithms, letting you inspect balances, review mini statements, and execute fast money transfers. Enjoy banking wherever you go, 24/7/365.
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 pt-4">
              {appFeatures.slice(0, 2).map((feat, idx) => (
                <div key={idx} className="space-y-1.5">
                  <div className="flex items-center gap-2">
                    {feat.icon}
                    <h4 className="font-bold text-slate-800 text-xs sm:text-sm">{feat.title}</h4>
                  </div>
                  <p className="text-xs text-slate-500 leading-relaxed font-normal">{feat.desc}</p>
                </div>
              ))}
            </div>
          </motion.div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {appFeatures.slice(2).map((feat, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: idx * 0.15 }}
                className="bg-white border border-slate-100 rounded-3xl p-6 shadow-sm hover:shadow-lg transition-all duration-300 space-y-4"
              >
                <div className="w-12 h-12 rounded-xl bg-slate-50 flex items-center justify-center border border-slate-100">
                  {feat.icon}
                </div>
                <div className="space-y-2">
                  <h3 className="font-bold text-slate-800 text-sm">{feat.title}</h3>
                  <p className="text-xs text-slate-500 leading-relaxed font-normal">{feat.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Section 2: Registration Guide */}
        <section className="bg-white border border-slate-100 rounded-3xl p-8 shadow-xs space-y-12">
          <div className="text-center max-w-2xl mx-auto">
            <h2 className="text-2xl font-extrabold text-slate-900">Registration & Setup</h2>
            <p className="text-slate-500 text-xs mt-2 font-normal">
              Activate your mobile banking profile safely in less than 5 minutes.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 relative">
            {registrationSteps.map((step, idx) => (
              <div key={idx} className="space-y-3 relative">
                <span className="text-3xl font-black text-slate-100 block">{`0${idx + 1}`}</span>
                <h4 className="font-bold text-slate-800 text-sm">{step.title}</h4>
                <p className="text-xs text-slate-500 leading-relaxed font-normal">{step.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Section 3: App Security Guidelines */}
        <section className="bg-slate-900 text-white rounded-3xl p-8 shadow-xl border border-slate-800 grid grid-cols-1 lg:grid-cols-2 gap-12 items-center relative overflow-hidden">
          <div className="absolute top-0 right-0 w-32 h-32 bg-primary/10 rounded-full blur-2xl" />
          <div className="space-y-6">
            <span className="inline-flex items-center gap-1 text-[10px] font-bold text-primary bg-sky-950/30 px-3 py-1 rounded-full border border-sky-900/50">
              <ShieldCheck className="size-3.5" /> APP SECURITY
            </span>
            <h2 className="text-2xl sm:text-3xl font-extrabold leading-tight">
              Protecting your digital assets is our primary goal
            </h2>
            <p className="text-slate-300 text-xs leading-relaxed font-normal">
              ASCB Mobile Banking is audited under strict guidelines. To preserve security, please follow our standard device protection checklist.
            </p>
          </div>
          
          <ul className="space-y-4 text-xs text-slate-300">
            {securityGuidelines.map((guide, idx) => (
              <li key={idx} className="flex items-start gap-2.5">
                <span className="w-1.5 h-1.5 bg-primary rounded-full mt-1.5 shrink-0" />
                <span className="leading-relaxed font-normal">{guide}</span>
              </li>
            ))}
          </ul>
        </section>

      </div>
    </div>
  )
}
